import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import { ClientLoading, Rtl, SWRProvider, Snack, theme } from "@/components";
import { CssBaseline } from "@mui/material";
import { Suspense } from "react";
import Loading from "./loading";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='fa' dir='rtl'>
      <body>
        <AppRouterCacheProvider> {/* for mui */}
          <Rtl> {/* for mui */}
            <ThemeProvider theme={theme}> {/* for mui */}
              <CssBaseline /> {/* for mui */}
              <Suspense fallback={<Loading />}> {/* for stream loading animation */}
                <Snack /> {/* for Snackbar notification */}
                <ClientLoading /> {/* for loading client form loading*/}
                {children}
              </Suspense>
            </ThemeProvider>
          </Rtl>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
